(provide 'alpha_theme)

(add-to-list 'custom-theme-load-path "~/work/github/emacs/alpha_emacs/theme/")
(load-theme 'zenburn t)
;(load-theme 'molokai t)
;(load-theme 'misterioso)
;(load-theme 'tango-dark)
;(load-theme 'adwaita t)
;(load-theme 'wheatgrass t)
;(load-theme 'monokai t)
