(add-to-list 'load-path "~/.emacs.d")
;(require 'auto-complete-autoloads)
(require 'go-autocomplete)
(require 'auto-complete-config)
;(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(ac-config-default)
